### ISSUE TITLE
Failed to open project, error: no build.gradle file found in (/bitrise/src)

### ISSUE THREAD

**Issue by novemio** [dzinek/bitrise-step-android-detekt#1]
I am using build.gradle.kt . 
I found the same issue for Lint. 
Check this https://github.com/bitrise-steplib/bitrise-step-android-lint/issues/11 .

**Comment by dzinek** [comment]
I will check it out, thanks.

**Comment by PawelDedio** [comment]
@dzinek Any updates in that topic?

**Comment by brendanw** [comment]
I am seeing the same issue when switching to build.gradle.kts

**Comment by brendanw** [comment]
https://github.com/TheAthletic/bitrise-step-android-detekt

Forked here to support build.gradle.kts

**Comment by dzinek** [comment]
@jschmid it looks good - merged.

Thanks for contribution and apologies for a delay. I did not have time to look at it. But now I am back to live.

**Comment by jschmid** [comment]
Thanks @dzinek !

Can you please do a release now ?

**Comment by dzinek** [comment]
As soon as I can - just after I finish my regular job. I hope that in the evening I have some time to run tests and prepare a contribution to main repo.

**Comment by jschmid** [comment]
Sure!

Thank you for your time :)

**Comment by dzinek** [comment]
Added PR in [bitrise-io/bitrise-steplib - android-detekt 0.0.3](https://github.com/bitrise-io/bitrise-steplib/pull/2441), waiting for approval.

I have also added #3 to update [bitrise-io/android-testing](https://github.com/bitrise-io/android-testing) and add Kotlin DSL project to test.
